name: "image_generation"
backend: "python"
max_batch_size: 4
input [
    {
        name: "input_image_text"
        data_type: TYPE_STRING
        dims: [ -1 ]
    }
]

output [
    {
        name: "output_generated_image"
        data_type: TYPE_FP16
        dims: [ -1, -1, -1]
    }
]

dynamic_batching {
    preferred_batch_size: [ 4 ]
    max_queue_delay_microseconds: 300000
  }

instance_group [
    {
        count: 1
        kind: KIND_GPU
        gpus : [0]
    }
]